---
project: 
  type: manuscript
  output-dir: docs
title: "ESS330: Lab 5 Proposals"
authors: 
  - name: Olivia Gilpin
    affiliation: Colorado State University
    roles: [writing]
    corresponding: true
  - name: Josh Ray
    affiliation: Colorado State University
    roles: [writing]
bibliography: references.bib
csl: apa-6th-edition.csl
manuscript:
  article: index.qmd
format:
  html:
    self-contained: true
execute:
  echo: true
editor: visual
---

## Proposal 1: Agriculture’s Contribution to Global GHG Emissions
Author: Olivia Gilpin

Justification: The emissions of Greenhouse Gases are primarily derived from various inputs into the atmosphere, heavily including inputs from agricultural processes (Filonchyk et al., 2024). The patterns of global production play a significant role in climate variability, which are affected by the flux of greenhouse gas emissions (Bhatti et al., 2024). Understanding the patterns of greenhouse gas emissions, with the connection to agricultural practices, and in correlation to climate variability, will give us an overview of the interconnected relationships (Gołasa et al., 2021). Exploring if agriculture practices would be affected by a decrease in non-agricultural activities that cause greenhouse gas emissions investigates whether influences such as industry, energy, and transportation could be direct mechanisms of change for agricultural practices. We need to explore these mechanisms of change in order to see the relationship between non-agricultural sources and agricultural methods. This research will inform various stakeholders, especially policymakers, of sustainable practices aimed at eliminating larger inputs that reduce climate resiliency. 

Research objective/question/hypothesis:The objective of this study is to evaluate the relationship between agricultural emissions and practices in correlation with reducing non-agricultural greenhouse gas emission sources. Through this research objective, the goal is to assess if a decrease in emissions from non-agricultural sources will influence agricultural emissions and sustainability. 

Would a decrease in non-agricultural greenhouse gas emissions influence agricultural emissions and sustainability?

Hypothesis: A decrease in non-agricultural greenhouse gas emissions will reduce agricultural contributions to greenhouse gas emissions.

Proposed Methods:Through examining the relationship between greenhouse gas emissions and agricultural practices, we would take a comparative and statistical analysis approach. This approach would include an initial establishment of emission baselines, utilizing the total greenhouse gas emissions from agriculture and the CO₂ emissions from agriculture (Data Commons, 2020). We would then utilize the data on global greenhouse gas emissions and analyze that in comparison to the research on climate variability effects from agricultural practices (Bhatti et al., 2024; Filonchyk et al., 2024; Gołasa et al., 2021; Data Commons, 2020). A cross-comparison of emissions by source in order to differentiate agricultural emissions from other sources, and if reductions in emissions from non-agricultural emissions have an influence on the total greenhouse gas outputs from agriculture. For the statistical analysis, we would run a correlation analysis, a regression model, and a mediating analysis to evaluate the empirical significance of relationships.

Expected Outcomes:The basis of this research is to identify a pattern between non-agricultural sources of greenhouse gas emissions and agricultural practices. This is essential to connect the relationships between sources of greenhouse gas emissions to contribute to sustainable agricultural practices implementation. We expect this research to be able to inform stakeholders, such as policymakers, about the best sustainable agricultural practices. 

## Proposal 2: Identifying Key Contributors to Global CO₂ Emissions Effects on Global Climate Systems
Author: Olivia Gilpin

Justification: Carbon Dioxide emissions are a key contributor to climate change, driven by anthropogenic effects, which have a significant contribution to overall global emissions (Omemen & Aldbbah, 2025). There are various drivers of anthropogenic climate change, and fossil fuel combustion, releasing the greenhouse gas carbon dioxide into the atmosphere, is a primary driver (Siddik et al., 2021). Narrowing down the sources of Carbon Dioxide emissions over a temporal scale of the recent five years will show us global trends for informing stakeholders on future regulation measures. Global climate systems must be further assessed for human influence and the correlation to global Carbon Dioxide emissions on ecosystem functions (Forster et al., 2024). Understanding the environmental consequences of Carbon Dioxide emissions impacts every sector of life on earth, in addition to the environmental impacts, such as economic, social, and cultural intersections (Yılmaz & Ozaner, 2025). Through further understanding of the interconnectedness of global Carbon Dioxide emissions, stakeholders can be better informed of combating the consequences and creating interdisciplinary frameworks. 

Research objective/question/hypothesis: The research objective of this study will examine the impact of Carbon Dioxide emissions, key contributors to global Carbon Dioxide emissions, and their effects on global climate systems. Emissions vary by source, which will analyze the effects of anthropogenic factors such as energy, agriculture, and transportation in correlation to ecosystem functions such as coastal ecology, carbon sequestration, and weather patterns. 

Do the varying sources of Carbon Dioxide emissions into the atmosphere have different effects on ecosystem functions based on source?

Hypothesis: Carbon Dioxide emissions effects on ecosystem functions will vary by the source of Carbon Dioxide emissions. 

Proposed Methods: Analyzing the effects on global climate systems through identifying key contributors to global Carbon Dioxide emissions will require obtaining data on global Carbon Dioxide emission rates, using five consecutive years (Data Commons). Ecosystem function data will be obtained to include carbon sequestration, weather patterns, and coastal ecology studies. Ecosystem data may be obtained from sources including Data Commons, NOAA, NASA, and IUCN.  Carbon Dioxide emissions will then be cross-analyzed through statistical analysis to assess the relationships between ecosystem functions and emissions. Correlation tests will be utilized, including a regression model and comparative analysis. These forms of statistical analysis will express the influence of emissions on environmental factors.

Expected Outcomes: The basis of this research intends to expand upon the effects of Carbon Dioxide emissions on global climate systems, creating frameworks that will better strategize and plan with global stakeholders. This research takes crucial factors of economic, cultural, social, and environmental into consideration in anthropogenic climate change. Providing this data will relay to stakeholders an analysis of the most to least impactful sources of global Carbon Dioxide Emissions for prioritization of future interventions, regulations, and policies. 

## Proposal 3:  Greenhouse Gas Emissions From Electricity Generation in the World
Author: Josh Ray

Justification: This project would be very important because electricity generation is the number 1 greenhouse gas polluting industry in the world.  This is the main critique of electric vehicles, it is that even though they release no emissions in combustion, they require a large amount of electricity which is largely generated by greenhouse gas polluting methods, the percentage of electricity generated by these methods varies greatly across many countries which the dataset accounts for.  We need a future with clean renewable energy and I believe examining just how much emissions are released from the non-renewable sources will show the problem very well.  In this project I will show just exactly how detrimental the energy sector is right now to our planets future and how we need to transition to cleaner energy sources in order to slow the effects of climate change.  A big part of this project will be identifying which countries rely on fossil fuel sources the most to generate electricity and how much emissions would drop globally with these countries transitioning towards cleaner energy generation methods. 

Research Question, objective, and hypothesis:
How many less tons of CO2 would be released into the atmosphere if the top 10 country polluters by tons of CO2 transitioned all their energy generation to non-emitting sources?

The objective is to determine how great of an impact the energy sector could make on the reduction of CO2 emissions by switching to cleaner sources.

My hypothesis is that if the top 10 CO2 emitting countries switched to non CO2 emitting energy generation the overall CO2 emissions on earth would drop by 20%.

Proposed Methods:
I will use two data sets to determine the overall global percentage of CO2 emission reduction would result from the top 10 emitting countries switching to clean energy.
https://climatetrace.org/inventory?subsector=electricity-generation&year_from=2023&year_to=2023&gas=co2e100
https://ourworldindata.org/grapher/annual-co2-emissions-per-country
The scope of my study is to use the data of total annual CO2 emissions in the world and then use my other dataset to filter it by emissions from  electricity generation, both datasets have country filters so we can determine the top 10 countries and go from there.  This will be using a temporal scale method.  The variables I have available are countries, emissions, percentage change, emissions per capita, and percentage of global use.

Expected Outcomes:
I expect the top 10 overall CO2 emitting countries to have a large portion of their emissions coming from energy creation. Using all the data I have I expect that if the top 10 overall emitting countries switched to 100% clean energy that the overall CO2 emissions on earth would drop by at least 20%.

## Proposal 4: Identifying How Economic Growth increases CO2 emissions.
Author: Josh Ray

Justification: It is no secret that developed nations emit far more CO2 emissions than developing nations.  This shows in the statistic that the US and China combined emit over 40% of CO2 in the entire globe.  This has been brought up a lot at UN conventions and many other places on the global stage where developing nations are demanding that developed nations do more to reduce their emissions that are affecting everybody on earth.  I think it is very important to examine how the increase of GDP in a nation coincides with increases in CO2 emissions, I believe this is true for both developed and developing nations.  This is important because as countries want to increase their GDP and have booming economies, we just determine ways to do so without completely destroying our planet for future generations to come.  Showing the correlation between the two could allow for ideas to be proposed on how to sustainably grow an economy.

Research Question, Objective, and Hypothesis: 
What is the ratio of GDP increase percentage to the percentage of CO2 emission increase?

The objective in answering this question is to examine how much emissions change with a country's GDP increasing.  This will allow us to examine the relationship between the two and be able to predict future emissions and prepare for them.

My hypothesis is that an increase in GDP percentage is a 1:1 ratio with an increase in CO2 emission percentage.

Proposed Methods: My method will include combining a dataset showing all the countries GDP change from 2022 to 2023 and a dataset showing percentage change in those countries overall CO2 emissions. 
https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG
https://climatetrace.org/inventory?year_from=2023&year_to=2023&gas=co2e100
The scope of my study is examining the 25 developed nations GDP and CO2 emission change from 2022-2023 as well as 25 developing nations so that we represent the entire global community well. This will be a temporal scale method.  The variables I have are developed/developing nation status, CO2 emissions, CO2 emissions % change, GDP percentage change.
Expected Outcomes:
I expect a 1:1 ratio of GDP increase and CO2 emission increase.  I expect very little to no difference between developing and developed nations ratios.  These outcomes can allow us to examine our world economy and find solutions to how we can increase a country's economies without sacrificing our world's future to do so.

## References

[@6e981dac0c1c4278bd4199223da966b8]


[@climatetrace_nodate]


[@filonchyk2024greenhouse]


[@forster2024indicators]


[@golasa2021sources]


[@nagelkerken2015global]


[@omemen2025climate]


[@ourworldindata_nodate]


[@siddik2021current]


[@yilmaz2025causality]


[@worldbank_nodate]



